import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // A library without a pages directory: nothing for this rule to check.
    rules: { "@next/next/no-html-link-for-pages": "off" },
  },
  globalIgnores([
    // Vendored shadcn/ui components, kept as generated.
    "src/components/ui/**",
    // Generated by drizzle-kit.
    "src/db/migrations/**",
  ]),
]);

export default eslintConfig;
